### NEW FEATURES
- transition to assuming all games are played on site
- box scores - player info lines view toggle?
    - flip to newspaper box scores if game over?
    - series page? games viewable from classic/league and team-season pages?
    - games played auto populate in series/season?
    - box scores available at series, season, player, team, league level?
    - advantages highlighted in game log rolls / tracked, throw rolls etc
    - no hitter watch
- player info lines on rosters/lineup panels etc? including current pts
- wave system banning
- points line graph
- mobile/small window score message over middle of diamond
    - mobile runner cards too big
    - diamond bounces up and down with available buttons
    - defense box populate on side of defensive player?
    - sandwich menu pushed off side on game pages on mobile
    - make sure boxes are in the right places on other diamonds too
- scribe with knowl edge of group chat? larrupin zane thornberg, forced "interviews" on transactions?
    - transaction history?
    - greatest games/ game notes?
- preseason rankings
- mlb stats of players
- simulate games for improvement of roster picker
- win probability graphs
- improve worst looking cards
- AI vibe of design of parts of site