#UI ENHANCEMENTS
#- use most recent dh / no dh lineup for team
#- list series score in scoreboard
- bullpen tired pitchers show control on card issue, between innings tiredness same on card and in lineup panel
- show current points on player card
- wooden spoon coloring on team pages still looks wrong
### NEW FEATURES
- captaincies (most rings then most appearances then most consec then fewest other team seasons? beginning tiebreak on future, tiebreak core squads)
    - player info lines on rosters?
- playoff scenarios
- box scores + advantage splits
    - series page? games viewable from classic/league and team-season pages?
    - advantages highlighted in game log rolls / tracked
    - no hitter watch
- mobile/small window score message over middle of diamond
    - mobile runner cards too big
    - diamond bounces up and down with available buttons
    - defense box populate on side of defensive player?
    - sandwich menu pushed off side on game pages on mobile
- scribe with knowledge of group chat? larrupin zane thornberg, forced "interviews" on transactions?
    - transaction history?
    - greatest games/ game notes?
- preseason rankings
- simulate games for improvement of roster picker
- wave system banning
- win probability graphs
- mlb stats of players







