#- bases loaded send runner from 3rd on tag and everything goes weird (1b -> 2b, 2b disappears, 3b out?)
    - also wrong -> speed c 1st / speed b 2nd, single, send speed b home, end up with batter disappearing?
#- SWING AWAY & game over message on game ending cs
#- look for stuck situations
#- consecutive IBB / bases bug
- recheck steal then tag
    - recheck tag then tag
    - recheck tag then advance
    - recheck tag then ibb
    - recheck steal for 3rd out
    - mobile score message over middle of diamond
    - mobile runner cards too big
    - cards flickering when switching sides mid inning (and all the time)
    - improve steal UI in simultaneous mode? throw rolls in general make the target clear?
    - change swing away to ROLL FOR SWING?
    - put "game 1" or whatever above team names in linescore
    - add rolls to game log
    - actual rolls more prominent in UI
    - defense box populate on side of defensive player?
- mva/lvsc better organized on league season pages
    - all time layout for spaceships/spoon
    - scott spaceship/spoon count wrong on dashboard
- player info lines on rosters?
    - "Players" page so you can see everyone sorted by rings, filtered by OB etc?
    - player cards with rings and team/league usage history, MVAs/LVSCs, captaincies (most rings then most appearances then most consec then fewest other team seasons? beginning tiebreak on future)
- playoff odds
- preseason rankings
- scribe with knowledge of group chat? larrupin zane thornberg, forced "interviews" on transactions?
    - transaction history?
    - greatest games/ game notes?


- simulate games for improvement of roster picker
- box scores + advantage splits
- tracking rolls over time
- wave system banning
- mobile notifications?
- win probability graphs
- mlb stats of players
- when detroit hits a homer it says ding dang donger
    - when helton homers the song plays






